apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    run: webapp

spec:
  type: NodePort
  selector:
    color: {{ .Values.production }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
